### ISSUE TITLE
ファーストビューがスマホの実機でバグる

### ISSUE THREAD

**Issue by h-jun01** [team-essence/TAoSK-LP#11]
# 概要

おそらくurlバーが大きくなったり小さくなったりで計算が崩れている
無理そうならスマホはアニメーションなしでも良い

**Comment by big-Miyabi** [comment]
Chromeでも再現可能

iPhoneXで途中までスクロール ⇨ Moto G4に変更 ⇨ iPhone Xに戻す

で同じ状態になる
